version: "3.9"
services:
  realsense_ros2:
    build:
      context: ..
      dockerfile: src/Dockerfile
      #target: librealsense
    tty: true
    volumes:
      - /dev:/dev
    network_mode: "host"
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
